package com.thisrpg.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thisrpg.db.Players;

import com.thisrpg.db.PlayersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig playersDaoConfig;

    private final PlayersDao playersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        playersDaoConfig = daoConfigMap.get(PlayersDao.class).clone();
        playersDaoConfig.initIdentityScope(type);

        playersDao = new PlayersDao(playersDaoConfig, this);

        registerDao(Players.class, playersDao);
    }
    
    public void clear() {
        playersDaoConfig.clearIdentityScope();
    }

    public PlayersDao getPlayersDao() {
        return playersDao;
    }

}
